### PR TITLE
actually hid the scroll bar ;-;

### PR DESCRIPTION
**Pull request by PndaBoi**
I just had the intention to make the scroll bar hidden and just copy pasted some css randomly :skull: 

it should be gone now :)

### CODE REVIEW

**Comment by PndaBoi** [comment]
oh and i disabled scrolling because why do people need to scroll :skull:

**Comment by billythegoat356** [comment]
thanks for your help bro

**Comment by PndaBoi** [comment]
anytime <3

**Comment by PndaBoi** [comment]
oh wait you didn't actually commit the changes lol...

**Pull request closed without merging**
